version: '3.9'

services:
  gobalance:
    image: flexstatmain/gobalance:v2
    volumes:
     - ./tor:/etc/tor
     - ./configs:/var/lib/tor/configs
     - ./frontend:/var/lib/tor/frontend_data
     - ./supervisor:/etc/supervisor/
     - ./onionbalance:/go/gobalance/pkg/onionbalance
    restart: always


